using System;

namespace Microsoft.Xrm.Sdk.Client
{
    /// <summary>Indicates that the assembly contains early-bound types generated by the CrmSvcUtil utility.</summary>
    [AttributeUsage(AttributeTargets.Assembly)]
    public sealed class ProxyTypesAssemblyAttribute : Attribute
    {
        private bool _containsSharedContracts;

        /// <summary>Initializes a new instance of the   <see cref="T:Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute"></see> class.</summary>
        public ProxyTypesAssemblyAttribute()
        {
        }

        internal ProxyTypesAssemblyAttribute(bool containsSharedContracts)
        {
            this._containsSharedContracts = containsSharedContracts;
        }

        internal bool ContainsSharedContracts
        {
            get
            {
                return this._containsSharedContracts;
            }
        }
    }
}