<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net6.0;net7.0;net8.0;net9.0;net10.0</TargetFrameworks>
    <LangVersion>10</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ProxySerializationSurrogate.cs" />
    <Compile Remove="NtlmHttp\Ntlm.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Memory" Version="4.5.5" />
    <PackageReference Include="System.Formats.Asn1" Version="8.0.2" Condition="'$(TargetFramework)' != 'netstandard2.0'" />
    <PackageReference Include="System.Security.Cryptography.Pkcs" Version="8.0.1" Condition="'$(TargetFramework)' != 'netstandard2.0'" />
    <PackageReference Include="System.ServiceModel.Http" Version="4.8.1" Condition="'$(TargetFramework)' == 'netstandard2.0'" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="4.7.1" Condition="'$(TargetFramework)' == 'netstandard2.0'" />
    <PackageReference Include="System.ServiceModel.Http" Version="4.10.3" Condition="'$(TargetFramework)' != 'netstandard2.0'" />
  </ItemGroup>

  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageId>Microsoft.Xrm.Sdk</PackageId>
    <Authors>Microsoft.Xrm.Sdk</Authors>
    <PackageReleaseNotes></PackageReleaseNotes>
    <RepositoryUrl></RepositoryUrl>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
</Project>
